apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor-deployment
spec:
  selector:
    matchLabels:
      app: webcolor-deploy
  template:
    metadata:
      labels:
        app: webcolor-deploy
    spec:
      containers:
      - name: webcolor
        image: fabricioveronez/web-page:green
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
